apiVersion: v1
kind: Secret
metadata:
  name: backend-secret-{{ .Release.Name }}
type: Opaque
stringData:
  google_client_id: {{ .Values.additional.google_client_id }}
  jwt_secret: {{ .Values.additional.jwt_secret }}
  algorithms: {{ .Values.additional.algorithms }}
