apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-{{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: frontend-{{ .Release.Name }}
  template:
    metadata:
      labels:
        app: frontend-{{ .Release.Name }}
    spec:
      containers:
        - name: frontend
          image: {{ .Values.frontend.image }}:{{ .Values.frontend.tag }}
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-{{ .Release.Name }}
spec:
  selector:
    app: frontend-{{ .Release.Name }}
  ports:
    - port: 3000
      targetPort: 80
