apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: overheard-backend:v1
          env:
            - name: DATABASE_URL
              value: "sqlite:///./sql_test_app.db"
            - name: ACCESS_TOKEN_EXPIRE_MINUTES
              value: "30"
            - name: GOOGLE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: google_client_id
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: jwt_secret
            - name: ALGORITHMS
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: algorithms
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend
  ports:
    - port: 8000
      targetPort: 8000
